/**
 * Scribe: Human-readable report generation for STREET_CYBER_SCAN
 * See: docs/STREET_CYBER_SCAN.md
 *
 * Converts technical CyberRiskAnalysis into plain-language Markdown
 * for non-technical small business owners.
 */

import { CyberRiskAnalysis, Severity } from "./types";

/**
 * Convert severity to human-friendly description
 */
function severityToText(severity: Severity): string {
  switch (severity) {
    case "high":
      return "**High Risk** – Immediate action recommended";
    case "medium":
      return "**Medium Risk** – Should be addressed soon";
    case "low":
      return "**Low Risk** – Minor improvements suggested";
  }
}

/**
 * Format date for report header
 */
function formatDate(date: Date): string {
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/**
 * Generate "Next Steps" section based on severity
 */
function generateNextSteps(severity: Severity): string {
  if (severity === "high") {
    return `## What You Should Do Next

Your website has security issues that need immediate attention. Here's what we recommend:

1. **Contact your web hosting provider** or IT support immediately to address the critical issues listed above.
2. **Prioritize HTTPS** – Make sure your website uses encrypted connections to protect your customers.
3. **Review exposed services** – Any database or remote access ports should not be publicly accessible.
4. **Schedule a security audit** – We can help you fix these issues and prevent future vulnerabilities.

**Need help?** Contact us for a free consultation to discuss remediation options and ongoing protection.`;
  }
  
  if (severity === "medium") {
    return `## What You Should Do Next

Your website has some security gaps that should be addressed. Here's what we recommend:

1. **Review the findings** with your web developer or hosting provider.
2. **Implement security headers** – These are easy fixes that provide important protection.
3. **Ensure HTTPS is properly configured** – Redirect all traffic to encrypted connections.
4. **Consider a security review** – We can help you strengthen your defenses.

**Want guidance?** Contact us to discuss how to improve your security posture.`;
  }
  
  return `## What You Should Do Next

Your website shows good basic security, but there's always room for improvement:

1. **Keep up the good work** – Continue monitoring and maintaining your security measures.
2. **Address the minor issues** noted above when convenient.
3. **Stay informed** – Security best practices evolve, so regular reviews are valuable.

**Want to stay ahead?** Contact us about ongoing security monitoring and maintenance.`;
}

/**
 * Main Scribe function: generate Markdown report
 */
export function renderMarkdownReport(analysis: CyberRiskAnalysis): string {
  const { domain, scannedAt, overallSeverity, issues, summary } = analysis;
  
  let markdown = `# Cyber Risk Scan Report

**Domain:** ${domain}  
**Scan Date:** ${formatDate(scannedAt)}  
**Overall Risk:** ${severityToText(overallSeverity)}

---

## Summary

${summary}

---

## Findings

`;
  
  if (issues.length === 0) {
    markdown += `No significant security issues were detected during this scan. Your website demonstrates good basic security hygiene.

Keep in mind that this is a surface-level scan. A comprehensive security audit would examine additional factors like:
- Application security (login systems, data handling)
- Content vulnerabilities (outdated plugins, known CVEs)
- Internal network security
- Data backup and disaster recovery

`;
  } else {
    issues.forEach((issue, index) => {
      markdown += `### ${index + 1}. ${issue.title}

**Category:** ${issue.category}  
**Severity:** ${issue.severity.toUpperCase()}

${issue.description}

`;
      if (issue.evidenceHint) {
        markdown += `*Technical note: ${issue.evidenceHint}*

`;
      }
    });
  }
  
  markdown += `---

${generateNextSteps(overallSeverity)}

---

## About This Scan

This is a non-intrusive, automated security reconnaissance performed by InfinitySoul. We check publicly accessible information about your domain, including:

- DNS configuration
- Web server accessibility
- Security headers and HTTPS setup
- Publicly exposed network services

This scan does NOT:
- Attempt to exploit vulnerabilities
- Access private information
- Perform intrusive testing
- Guarantee detection of all issues

For a comprehensive security assessment, contact us about our full audit services.

---

*Report generated by InfinitySoul Cyber Risk Scanner*  
*${scannedAt.toISOString()}*
`;
  
  return markdown;
}
