import axios from "axios";
import { logger } from "../logger";

interface LobAddress {
  name: string;
  address_line1: string;
  address_line2?: string;
  city: string;
  state: string;
  zip: string;
}

interface LobLetterRequest {
  to: LobAddress;
  from: LobAddress;
  file: string; // HTML string or URL
  color?: boolean;
  double_sided?: boolean;
  mail_type?: "usps_first_class" | "usps_standard";
  certified?: boolean;
  return_envelope?: boolean;
}

interface LobLetterResponse {
  id: string;
  tracking_code: string;
  status: string;
  expected_delivery_date: string;
  cost: number; // in cents
  to: LobAddress;
  from: LobAddress;
  mail_type: string;
}

const LOB_API_KEY = process.env.LOB_API_KEY;
const LOB_BASE_URL = "https://api.lob.com/v1";

// Default sender address (from your company)
const DEFAULT_FROM_ADDRESS: LobAddress = {
  name: "WCAG AI Platform",
  address_line1: "123 Accessibility Lane",
  city: "San Francisco",
  state: "CA",
  zip: "94102",
};

async function validateLobApiKey(): Promise<boolean> {
  if (!LOB_API_KEY) {
    logger.error("LOB_API_KEY not configured");
    return false;
  }
  return true;
}

export async function sendCertifiedMail(
  recipientName: string,
  companyName: string,
  address: {
    line1: string;
    line2?: string;
    city: string;
    state: string;
    postalCode: string;
  },
  content: {
    subject: string;
    htmlBody: string;
    attachmentUrl?: string;
  },
  mailType: "certified" | "standard" | "priority" = "certified"
): Promise<{
  success: boolean;
  letterId?: string;
  trackingCode?: string;
  cost?: number;
  error?: string;
  estimatedDelivery?: string;
}> {
  try {
    if (!await validateLobApiKey()) {
      return {
        success: false,
        error: "LOB_API_KEY not configured. Please set up Lob integration.",
      };
    }

    const recipient: LobAddress = {
      name: recipientName,
      address_line1: address.line1,
      address_line2: address.line2,
      city: address.city,
      state: address.state,
      zip: address.postalCode,
    };

    // Build HTML template with subject and content
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            h1 { color: #333; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
            .content { margin: 20px 0; }
            .footer { margin-top: 40px; font-size: 12px; color: #666; border-top: 1px solid #ddd; padding-top: 20px; }
          </style>
        </head>
        <body>
          <h1>${content.subject}</h1>
          <div class="content">
            ${content.htmlBody}
          </div>
          <div class="footer">
            <p>WCAG Accessibility Audit Report</p>
            <p>This document was generated by the WCAG AI Platform</p>
          </div>
        </body>
      </html>
    `;

    // Prepare request to Lob API
    const params = new URLSearchParams();
    params.append("to[name]", recipient.name);
    params.append("to[address_line1]", recipient.address_line1);
    if (recipient.address_line2) {
      params.append("to[address_line2]", recipient.address_line2);
    }
    params.append("to[city]", recipient.city);
    params.append("to[state]", recipient.state);
    params.append("to[zip]", recipient.zip);

    params.append("from[name]", DEFAULT_FROM_ADDRESS.name);
    params.append("from[address_line1]", DEFAULT_FROM_ADDRESS.address_line1);
    params.append("from[city]", DEFAULT_FROM_ADDRESS.city);
    params.append("from[state]", DEFAULT_FROM_ADDRESS.state);
    params.append("from[zip]", DEFAULT_FROM_ADDRESS.zip);

    params.append("file", htmlContent);
    params.append("color", "true");
    params.append("double_sided", "true");

    // Set mail type based on user preference
    if (mailType === "certified") {
      params.append("mail_type", "usps_first_class");
      params.append("certified", "true");
      params.append("return_envelope", "true");
    } else if (mailType === "priority") {
      params.append("mail_type", "usps_first_class");
    } else {
      params.append("mail_type", "usps_standard");
    }

    const response = await axios.post(`${LOB_BASE_URL}/letters`, params, {
      auth: {
        username: LOB_API_KEY,
        password: "",
      },
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
    });

    const data = response.data;

    logger.info(`Certified mail sent successfully`, {
      letterId: data.id,
      trackingCode: data.tracking_code,
      recipient: recipient.name,
    });

    return {
      success: true,
      letterId: data.id,
      trackingCode: data.tracking_code,
      cost: data.cost,
      estimatedDelivery: data.expected_delivery_date,
    };
  } catch (error) {
    logger.error("Failed to send certified mail", error as Error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

export async function getMailStatus(
  letterId: string
): Promise<{
  success: boolean;
  status?: string;
  trackingCode?: string;
  estimatedDelivery?: string;
  error?: string;
}> {
  try {
    if (!await validateLobApiKey()) {
      return {
        success: false,
        error: "LOB_API_KEY not configured",
      };
    }

    const response = await axios.get(`${LOB_BASE_URL}/letters/${letterId}`, {
      auth: {
        username: LOB_API_KEY,
        password: "",
      },
    });

    const data = response.data;

    return {
      success: true,
      status: data.status,
      trackingCode: data.tracking_code,
      estimatedDelivery: data.expected_delivery_date,
    };
  } catch (error) {
    logger.error("Failed to get mail status", error as Error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

export async function createBulkCertifiedMailCampaign(
  recipients: Array<{
    name: string;
    company: string;
    address: {
      line1: string;
      line2?: string;
      city: string;
      state: string;
      postalCode: string;
    };
  }>,
  content: {
    subject: string;
    htmlBody: string;
  },
  mailType: "certified" | "standard" | "priority" = "certified"
): Promise<{
  success: boolean;
  campaignId?: string;
  totalRecipients?: number;
  sentCount?: number;
  failedCount?: number;
  results?: Array<{
    recipient: string;
    letterId?: string;
    trackingCode?: string;
    error?: string;
  }>;
}> {
  try {
    if (!await validateLobApiKey()) {
      return {
        success: false,
        results: [],
      };
    }

    const results = [];
    let sentCount = 0;
    let failedCount = 0;

    for (const recipient of recipients) {
      const result = await sendCertifiedMail(
        recipient.name,
        recipient.company,
        recipient.address,
        content,
        mailType
      );

      if (result.success) {
        results.push({
          recipient: recipient.name,
          letterId: result.letterId,
          trackingCode: result.trackingCode,
        });
        sentCount++;
      } else {
        results.push({
          recipient: recipient.name,
          error: result.error,
        });
        failedCount++;
      }

      // Add small delay to avoid rate limiting (100ms between requests)
      await new Promise((resolve) => setTimeout(resolve, 100));
    }

    logger.info("Bulk certified mail campaign completed", {
      totalRecipients: recipients.length,
      sentCount,
      failedCount,
    });

    return {
      success: sentCount > 0,
      totalRecipients: recipients.length,
      sentCount,
      failedCount,
      results,
    };
  } catch (error) {
    logger.error("Failed to create bulk campaign", error as Error);
    return {
      success: false,
      totalRecipients: recipients.length,
      sentCount: 0,
      failedCount: recipients.length,
      results: [],
    };
  }
}

export async function estimateMailCost(
  mailType: "certified" | "standard" | "priority" = "certified"
): Promise<{ cost: number; description: string }> {
  // Approximate costs (actual costs may vary)
  const costs: Record<string, { cost: number; description: string }> = {
    certified: {
      cost: 390, // $3.90
      description: "USPS Certified Mail with Return Receipt",
    },
    priority: {
      cost: 840, // $8.40
      description: "USPS Priority Mail Express",
    },
    standard: {
      cost: 170, // $1.70
      description: "USPS Standard Mail",
    },
  };

  return costs[mailType] || costs.certified;
}
