import { logger } from '../logger';

export interface VpatRequest {
  productName: string;
  productVersion?: string;
  vendorName: string;
  wcagLevel: 'A' | 'AA' | 'AAA';
  scanResults: {
    totalViolations: number;
    criticalCount: number;
    seriousCount: number;
    moderateCount: number;
    minorCount: number;
    wcagScore: number;
  };
}

export const vpatService = {
  /**
   * Generate VPAT 2.4 HTML document
   */
  generateVpatHtml(request: VpatRequest): string {
    const reportDate = new Date().toISOString().split('T')[0];
    const complianceLevel = this.getComplianceLevel(request.wcagScore);
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VPAT - ${request.productName}</title>
  <style>
    body { 
      font-family: Arial, sans-serif; 
      line-height: 1.6; 
      color: #333; 
      margin: 0; 
      padding: 20px;
      background: #f5f5f5;
    }
    .container { 
      max-width: 900px; 
      margin: 0 auto; 
      background: white; 
      padding: 40px; 
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1, h2, h3 { color: #1a202c; }
    h1 { border-bottom: 3px solid #10b981; padding-bottom: 10px; }
    .section { margin-bottom: 30px; }
    .metadata { background: #f9fafb; padding: 15px; border-radius: 4px; margin-bottom: 20px; }
    .metadata p { margin: 5px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
    th { background: #f3f4f6; font-weight: bold; }
    tr:hover { background: #f9fafb; }
    .compliant { color: #10b981; font-weight: bold; }
    .partial { color: #f59e0b; font-weight: bold; }
    .non-compliant { color: #ef4444; font-weight: bold; }
    .score-box { 
      background: linear-gradient(135deg, #10b981 0%, #059669 100%); 
      color: white; 
      padding: 20px; 
      border-radius: 8px; 
      text-align: center; 
      margin: 20px 0;
    }
    .score-box .number { font-size: 48px; font-weight: bold; }
    .score-box .label { font-size: 16px; opacity: 0.9; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Voluntary Product Accessibility Template (VPAT®) 2.4</h1>
    
    <div class="metadata">
      <p><strong>Product Name:</strong> ${request.productName} ${request.productVersion ? 'v' + request.productVersion : ''}</p>
      <p><strong>Vendor Name:</strong> ${request.vendorName}</p>
      <p><strong>Report Date:</strong> ${reportDate}</p>
      <p><strong>VPAT Version:</strong> 2.4</p>
      <p><strong>WCAG Target Level:</strong> ${request.wcagLevel}</p>
      <p><strong>Generated By:</strong> Accessibility AI Platform</p>
    </div>

    <div class="section">
      <h2>Conformance Summary</h2>
      <div class="score-box">
        <div class="number">${request.wcagScore}%</div>
        <div class="label">Overall Accessibility Compliance</div>
      </div>
      
      <p><strong>Compliance Status:</strong> <span class="${this.getStatusClass(request.wcagScore)}">${complianceLevel}</span></p>
      
      <h3>Violations Breakdown</h3>
      <table>
        <tr>
          <th>Severity Level</th>
          <th>Count</th>
          <th>Impact</th>
        </tr>
        <tr>
          <td>Critical</td>
          <td>${request.scanResults.criticalCount}</td>
          <td>Blocks access or understanding</td>
        </tr>
        <tr>
          <td>Serious</td>
          <td>${request.scanResults.seriousCount}</td>
          <td>Significantly impairs access</td>
        </tr>
        <tr>
          <td>Moderate</td>
          <td>${request.scanResults.moderateCount}</td>
          <td>Somewhat impairs access</td>
        </tr>
        <tr>
          <td>Minor</td>
          <td>${request.scanResults.minorCount}</td>
          <td>Minor impact on access</td>
        </tr>
        <tr style="font-weight: bold; background: #f3f4f6;">
          <td>Total Violations</td>
          <td>${request.scanResults.totalViolations}</td>
          <td>Across all severity levels</td>
        </tr>
      </table>
    </div>

    <div class="section">
      <h2>WCAG ${request.wcagLevel} Compliance Details</h2>
      
      <h3>Perceivable (Principle 1)</h3>
      <p>Information and user interface components must be presentable to users in ways they can perceive.</p>
      <p><strong>Status:</strong> <span class="${this.getStatusClass(request.wcagScore)}">Substantially Conforms</span></p>
      
      <h3>Operable (Principle 2)</h3>
      <p>User interface components and navigation must be operable.</p>
      <p><strong>Status:</strong> <span class="${this.getStatusClass(request.wcagScore)}">Substantially Conforms</span></p>
      
      <h3>Understandable (Principle 3)</h3>
      <p>Information and the operation of user interface must be understandable.</p>
      <p><strong>Status:</strong> <span class="${this.getStatusClass(request.wcagScore)}">Substantially Conforms</span></p>
      
      <h3>Robust (Principle 4)</h3>
      <p>Content must be robust enough that it can be interpreted reliably by a wide variety of user agents, including assistive technologies.</p>
      <p><strong>Status:</strong> <span class="${this.getStatusClass(request.wcagScore)}">Substantially Conforms</span></p>
    </div>

    <div class="section">
      <h2>Recommendations</h2>
      <ul>
        ${request.scanResults.criticalCount > 0 ? '<li><strong>Priority 1:</strong> Address all critical violations immediately - these block access for many users</li>' : ''}
        ${request.scanResults.seriousCount > 0 ? '<li><strong>Priority 2:</strong> Resolve serious violations within 2 weeks to significantly improve accessibility</li>' : ''}
        ${request.scanResults.moderateCount > 0 ? '<li><strong>Priority 3:</strong> Fix moderate violations within 30 days for continuous improvement</li>' : ''}
        <li><strong>Ongoing:</strong> Implement automated accessibility testing in your CI/CD pipeline to catch issues early</li>
        <li><strong>Training:</strong> Educate development team on WCAG principles for sustainable compliance</li>
      </ul>
    </div>

    <div class="footer">
      <p>This VPAT was generated by the Accessibility AI Platform using automated scanning technology combined with WCAG guidelines.</p>
      <p>For questions or additional details, contact your accessibility consultant or visit wcagai.com</p>
      <p>© ${new Date().getFullYear()} Accessibility AI. VPAT is a registered trademark of the Information Technology Industry Council.</p>
    </div>
  </div>
</body>
</html>`;
  },

  /**
   * Determine compliance level text
   */
  getComplianceLevel(wcagScore: number): string {
    if (wcagScore >= 95) return 'Fully Conforms';
    if (wcagScore >= 90) return 'Substantially Conforms';
    if (wcagScore >= 70) return 'Partially Conforms';
    return 'Does Not Conform';
  },

  /**
   * Get CSS class for status display
   */
  getStatusClass(wcagScore: number): string {
    if (wcagScore >= 90) return 'compliant';
    if (wcagScore >= 70) return 'partial';
    return 'non-compliant';
  },

  /**
   * Generate VPAT as downloadable text
   */
  generateVpatMarkdown(request: VpatRequest): string {
    const reportDate = new Date().toISOString().split('T')[0];
    
    return `# Voluntary Product Accessibility Template (VPAT®) 2.4

## Product Information
- **Product Name:** ${request.productName} ${request.productVersion ? 'v' + request.productVersion : ''}
- **Vendor:** ${request.vendorName}
- **Report Date:** ${reportDate}
- **WCAG Target:** ${request.wcagLevel}

## Compliance Summary
**Overall Score:** ${request.wcagScore}%
**Status:** ${this.getComplianceLevel(request.wcagScore)}

### Violation Breakdown
| Severity | Count | Impact |
|----------|-------|--------|
| Critical | ${request.scanResults.criticalCount} | Blocks access or understanding |
| Serious | ${request.scanResults.seriousCount} | Significantly impairs access |
| Moderate | ${request.scanResults.moderateCount} | Somewhat impairs access |
| Minor | ${request.scanResults.minorCount} | Minor impact on access |
| **Total** | **${request.scanResults.totalViolations}** | **All severity levels** |

## WCAG ${request.wcagLevel} Details
### Perceivable (Principle 1)
Information and user interface components must be presentable to users in ways they can perceive.
**Status:** Substantially Conforms

### Operable (Principle 2)  
User interface components and navigation must be operable.
**Status:** Substantially Conforms

### Understandable (Principle 3)
Information and the operation of user interface must be understandable.
**Status:** Substantially Conforms

### Robust (Principle 4)
Content must be robust enough for reliable interpretation by various user agents.
**Status:** Substantially Conforms

## Recommendations
${request.scanResults.criticalCount > 0 ? '- **Priority 1:** Address critical violations immediately\n' : ''}
${request.scanResults.seriousCount > 0 ? '- **Priority 2:** Resolve serious violations within 2 weeks\n' : ''}
${request.scanResults.moderateCount > 0 ? '- **Priority 3:** Fix moderate violations within 30 days\n' : ''}
- Implement automated accessibility testing in CI/CD pipeline
- Educate development team on WCAG principles

---
*Generated by Accessibility AI Platform*
`;
  },
};
